[package]
name = "synulator"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]
edition = "2018"

[dependencies]
synapse-rpc = { path = "../rpc" }
serde_json = "1"
rand = "0.9.1"
ws = "0.7"
